### PR TITLE
Multiple cause areas

### LINKED ISSUE #608: Wrap up reconstruction of multiple cause area backup changes

### PR DESCRIPTION
**Pull request by fellmirr**
Creating a draft of this. We might want to merge this into dev rather than main and test all the changes there. Especially since we have dependant frontend changes that might be nice to test against this.

This breaks a ton of stuff, but right now I got donation registration working. Will make separate issues and PR's for fixing the broken functionality.

- closes #608 
---

Tested on devices

- [ ] Desktop 💻
- [ ] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

Checkpoints

_Check these to flag for a more thurough review, as they could be potentially breaking changes_

- [ ] Packages updated
- [ ] Other infrastructure updated (such as node version or similar)

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by adamalfredsson** [comment]
That's alright, probably necessary to use it in the both seed and migration script.

Maybe it's too late for consideration, but I think a good way to go about database migrations is by using a [expand and contract pattern](https://www.prisma.io/dataguide/types/relational/expand-and-contract-pattern). That way we would just expand the schema in our first migration, then copy data over to the new schema separately from the migration interface.

The current approach should work too, it would just be a little rough if the migration fails for whatever reason since it's not transactional. For example, we could end up in a state where the migration fails after doing some destructive actions. This would mean the backend breaks in production.

**Comment by fellmirr** [comment]
> Maybe it's too late for consideration, but I think a good way to go about database migrations is by using a [expand and contract pattern](https://www.prisma.io/dataguide/types/relational/expand-and-contract-pattern). That way we would just expand the schema in our first migration, then copy data over to the new schema separately from the migration interface.

That's a great article, thanks! Indeed, with such a large change this might have been more prudent. It's more overhead, but safer. It also solves some of the issue with having prod in a broken stage indeed!

It would also make it possible to gradually transition functionality. One would have to write some specialised logic on both the frontend and backend to handle this, but it might be worth it in the end.

My approach was simply to copy down the prod schema and make sure that the migration ran locally, but obviously not everyone can do this. For example volunteers developers that only need to work with the static test dataset.

> Ideally, this should involve small changes to the existing structure. Larger changes should be broken up into smaller, isolated steps which can each run through this process in succession.

Oops, 👀 

Learning a lot about DB migrations, this is all fairly new to me!

**Comment by fellmirr** [comment]
Also, if I've made some mistake and accidentally destroyed data, keeping the old one around IN the prod schema for some time would be neat. My plan has been to simply backup a dump, just to be sure.

**Comment by adamalfredsson** [comment]
I mean, since we're a small team and working on the same thing here, I don't think the current approach is necessarily bad, it's actually pretty clever! As long as you can pull a copy of the prod data and demonstrate a successful migration locally, then we should be fairly confident in the migration result. In worst case we can just rollback to a backup. We should also probably close the backend during this migration.

If anything, I would suggest we keep the API interface intact with this work. So for example, in the donation registration route, we don't expect cause areas in the input, but rather we use the current input and mold it to fit the new database schema. Then we can make gradual changes in the API at later stages. Do you think that would be feasible?

**Comment by adamalfredsson** [comment]
Perhaps we can keep `master` as base branch and rebase `dev` onto this branch instead?

**Comment by fellmirr** [comment]
> Perhaps we can keep master as base branch and rebase dev onto this branch instead?

Ah, I've never really used rebase. As far as I understand it's related to keeping a nicer git history that's easier to reason about? So in this case we'd roll back the merge commit, rebase dev to this branch to test it out, and then we can keep working on this branch rather than dev? Something like that? What are the benefits of that approach? 😄

**Comment by adamalfredsson** [comment]
Yes, I'm thinking we're just mostly interested in deploying this to `dev`, but we still want to merge this PR eventually to `master`. It seems like `dev` has some changes already (perhaps we can toss these though?). For example, when we merge `dev` into this branch, we will get those changes into this PR too. I guess the bottom line, is that we really don't want any changes from `dev` merged into this branch, right?

**Comment by adamalfredsson** [comment]
It can be a little tricky to get into rebasing, let me know if you want me to do it!

**Comment by fellmirr** [comment]
Looks like the dev brach has some semgrep related changes that have not been merged to master yet. Other than that, looking over the merge commits, it seems mostly to be changes from master that have been merged in (since I updated dev to master first, then merged dev into this one). 

But we definetly don't really want semgrep to be in this branch, as it's totally unrelated. If you want to clean it up, I say go ahead! And I'll read up on rebasing on the plane 😎

**Comment by fellmirr** [comment]
It was neat that it caught a potential injection though! In this case a false positive, but it's a nice little helper.

**Comment by adamalfredsson** [comment]
Hm what? No panic, it's still there, but not sure why GitHub thought it was deleted after rebasing the dev branch :/

**Comment by adamalfredsson** [comment]
Ah, likely because I didn't change the base branch before rebase :(

**Comment by adamalfredsson** [comment]
It's unfortunate that there's no way to reopen a PR once "merged". I think we might have to create a new one.

**Comment by adamalfredsson** [comment]
So actually Github deleted the branch too. This took a bit of a more chaotic turn than I expected, but the branch is restored with a new PR at #622 and `dev` is rebased. I think I'm a little confused about the implication of base branches on Github PRs.

**Pull request merged**
