### PR TITLE
Change full name index length

### LINKED ISSUE #587: Unable to push database schema
When running `npx prisma db push`, I get the following error:

```
⋊> ~/P/g/e/effekt-backend on master ⨯ npx prisma db push --force-reset                                                                                            14:24:01
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "EffektDonasjonDB_Local" at "localhost:3306"

The MySQL database "EffektDonasjonDB_Local" at "localhost:3306" was successfully reset.
Error: Specified key was too long; max key length is 255 bytes
   0: sql_schema_connector::apply_migration::migration_step
           with step=CreateTable { table_id: TableId(9) }
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:21
   1: sql_schema_connector::apply_migration::apply_migration
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:10
   2: schema_core::state::SchemaPush
             at schema-engine/core/src/state.rs:433
```

### PR DESCRIPTION
**Pull request by adamalfredsson**
- closes #587

When searching for this issue I found someone suggesting TinyText column type [could be the issue](https://stackoverflow.com/a/46157273/7776268). After trying it, it seems like the issue is resolved. Is it safe to perform this migration though?

---

Tested on devices

- [ ] Desktop 💻
- [ ] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

Checkpoints

_Check these to flag for a more thurough review, as they could be potentially breaking changes_

- [ ] Packages updated
- [ ] Other infrastructure updated (such as node version or similar)

⏲️ Time spent on CR:

⏲️ Time spent on QA:

### CODE REVIEW

**Comment by fellmirr** [comment]
I remember this being a limitation. In the production database the key length is 67 (which doesn't actually strongly guarantee unique emails, but I think I settled for it being good enough).
There is some weirdness going on around this, but for the life of mye I don't remember what it was. Is it possible for us to just match the DB schema, and explicitly set the key length to 67?

**Comment by adamalfredsson** [comment]
> Ah, yes, I remember why we need tinytext. It's for mysql fulltext search. So we can't change it to varchar without breaking some search functionality. I'll try to see if I get the same issues on my machine, and if it's possible to resolve it :)

Bummer! Yes, didn't do much further investigation so hopefully there are other alternatives!

**Comment by fellmirr** [comment]
Looks like simply changing the index lengths to 63 solves the issue!

Maybe you can update the PR with that change? I think that's fine. Looks like the `full_name` column was the offender.

**Review by fellmirr — APPROVED** [review]
:+1:

**Pull request merged**
