### PR TITLE
Adds sum and count to donors/id/distribution route

### PR DESCRIPTION
**Pull request by philiphand**

### CODE REVIEW

**Comment by fellmirr** [comment]
@philiphand Hva er det denne endringen er for?

**Comment by philiphand** [comment]
Den er for admin-panelet, distribution table

**Comment by philiphand** [comment]
På siden for individuell donor

**Comment by philiphand** [comment]
Turns out a new route would be redundant and that the admin panel was simply sending requests to the wrong route.

**Pull request closed without merging**
